# Generated by Django 5.1.6 on 2025-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_friendrequest_userlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_in_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message_privacy',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('friends', 'Friends Only'), ('none', 'No One')], default='everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='public', max_length=10),
        ),
    ]
